### ISSUE TITLE
the means of the k-shot

### ISSUE THREAD

**Issue by cuixianheng** [yiweilu3/Few-shot-Scene-adaptive-Anomaly-Detection#1]
I want to know the means of the K-shot in the orignal papers "Few-Shot Scene-Adaptive Anomaly Detection", thank you!

**Comment by yiweilu3** [comment]
Hi,

K-shot refers to the number of training samples for adaptation in testing time. We have submitted the paper on arxiv, feel free to take a look.

Best regards,

Yiwei

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cuixianheng** [comment]
thank you，I want to know whether the number of training samples and test samples is K during meta-training and meta-testing？

**Comment by yiweilu3** [comment]
Yes, we use k-shot for meta-learning, meta-validation and meta-testing.
________________________________

**Comment by cuixianheng** [comment]
I get it，thank you very much.

**Comment by yiweilu3** [comment]
No problem ??
________________________________
