### ISSUE TITLE
question on function 'createEpochData' 

### ISSUE THREAD

**Issue by abhishekaich27** [yiweilu3/Few-shot-Scene-adaptive-Anomaly-Detection#11]
What is happening in these lines 
```
for task in range(numTasks):
        sample = random.sample(list(os.listdir(os.path.join(frame_path, dirs[task]))), 1)
        selected_videos.append(os.path.join(frame_path, dirs[task], sample[0]))
```
```frame path``` is the folder path which contains extracted frames of all training videos (referring Shanghai-Tech dataset) stored inside folders with video IDs as name of the folder. ```dirs``` is randomly selecting video folder names (each folder contains extracted frames at 24 fps in jpg format). But then, what we doing with the for loop above? What is being selected from the variable ```sample```? Printing ```sample``` gives me a randomly selected frame. From my understanding of the variable names, ```selected_videos``` should contain path to videos right? and not to particular frames? I have the following example outputs from your code.   
e.g. 
```frame-path='/dataset/shanghaitech/training/frames/'```
```dirs=['08_003', '08_004', '08_005', '08_006', '08_007', '08_008', '08_009', '08_010', '08_011', '08_012', '08_013', '08_014', '08_015', '08_016', '08_017', '08_018']``` 
```selected_videos=['/dataset/shanghaitech/training/frames/01_001/0080.jpg', '/dataset/shanghaitech/training/frames/01_002/0028.jpg', '/dataset/shanghaitech/training/frames/01_003/0563.jpg']```

Can you help me refactor the code @yiweilu3, @yu-frank  ?

**Comment by abhishekaich27** [comment]
> What is happening in these lines
> 
> ```
> for task in range(numTasks):
>         sample = random.sample(list(os.listdir(os.path.join(frame_path, dirs[task]))), 1)
>         selected_videos.append(os.path.join(frame_path, dirs[task], sample[0]))
> ```
> 
> `frame path` is the folder path which contains extracted frames of all training videos (referring Shanghai-Tech dataset) stored inside folders with video IDs as name of the folder. `dirs` is randomly selecting video folder names (each folder contains extracted frames at 24 fps in jpg format). But then, what we doing with the for loop above? What is being selected from the variable `sample`? Printing `sample` gives me a randomly selected frame. From my understanding of the variable names, `selected_videos` should contain path to videos right? and not to particular frames? I have the following example outputs from your code.
> e.g.
> `frame-path='/dataset/shanghaitech/training/frames/'`
> `dirs=['08_003', '08_004', '08_005', '08_006', '08_007', '08_008', '08_009', '08_010', '08_011', '08_012', '08_013', '08_014', '08_015', '08_016', '08_017', '08_018']`
> `selected_videos=['/dataset/shanghaitech/training/frames/01_001/0080.jpg', '/dataset/shanghaitech/training/frames/01_002/0028.jpg', '/dataset/shanghaitech/training/frames/01_003/0563.jpg']`
> 
> Can you help me refactor the code @yiweilu3 ?

I think this question can be better understood by how you create the folder ```shanghaitech-5tasks```, Can you provide the train/test split for your settings?

**Comment by zzzzyq-18** [comment]
> > 这些线路中发生了什么
> > ```
> > for task in range(numTasks):
> >         sample = random.sample(list(os.listdir(os.path.join(frame_path, dirs[task]))), 1)
> >         selected_videos.append(os.path.join(frame_path, dirs[task], sample[0]))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `frame path`是文件夹路径，其中包含存储在以视频 ID 为文件夹名称的文件夹中的所有训练视频（参考 Shanghai-Tech 数据集）的提取帧。`dirs`随机选择视频文件夹名称（每个文件夹包含 jpg 格式的 24 fps 提取帧）。但是，我们对上面的 for 循环做了什么？从变量中选择了`sample`什么？打印`sample`给了我一个随机选择的框架。根据我对变量名称的理解，`selected_videos`应该包含视频的路径吗？而不是特定的框架？我从您的代码中得到以下示例输出。
> > 例如
> > `frame-path='/dataset/shanghaitech/training/frames/'`
> > `dirs=['08_003', '08_004', '08_005', '08_006', '08_007', '08_008', '08_009', '08_010', '08_011', '08_012', '08_013', '08_014', '08_015', '08_016', '08_017', '08_018']`
> > `selected_videos=['/dataset/shanghaitech/training/frames/01_001/0080.jpg', '/dataset/shanghaitech/training/frames/01_002/0028.jpg', '/dataset/shanghaitech/training/frames/01_003/0563.jpg']`
> > 你能帮我重构代码@yiweilu3吗？
> 
> 我认为通过您如何创建文件夹可以更好地理解这个问题，您`shanghaitech-5tasks`能否为您的设置提供训练/测试拆分？

excuse me ,I want to ask you, you solved this problem? I met the same problem
