### ISSUE TITLE
the code problem of the timestep

### ISSUE THREAD

**Issue by cuixianheng** [yiweilu3/Few-shot-Scene-adaptive-Anomaly-Detection#2]
in your code, the input of the convlstm is a 4d tensor and the first dimension is the timestep--t, but you don't write the code: 
for t in range(0,seq_len), i want to know why.

**Comment by yiweilu3** [comment]
Sorry I didn't see the message. The range of t actually iterate in the forward function, you can take a look in the rGAN.py code.
