### ISSUE TITLE
About complete code

### ISSUE THREAD

**Issue by lonelyhope** [yiweilu3/Few-shot-Scene-adaptive-Anomaly-Detection#5]
I'm interested in your work and may I ask when the complete code will be published? Thanks for reply.

**Comment by yiweilu3** [comment]
Thank you for your interest! I am super busy these days but I will try to clean and upload the complete code around October.

**Comment by lonelyhope** [comment]
I got it, thank you very much for your reply!

**Comment by ZeWang95** [comment]
Dear authors,

when can we expect to see the completed implementations?

Thanks!
